#!/usr/bin/env bash
#
# setup-apt-signing-key.sh
#
# One-time helper to create the GPG signing key for the oob-usb-serial APT
# repository and wire it into GitHub Actions.
#
# WHAT THIS DOES
#   1. Generates a dedicated GPG signing key pair (no passphrase by default so
#      it can be used non-interactively in CI; you may set one).
#   2. Exports the ASCII-armored PUBLIC key to docs/apt/pubkey.gpg (committed to
#      the repo and served to users so they can trust the archive).
#   3. Exports the ASCII-armored PRIVATE key to a local file and tells you how
#      to store it as the GitHub Actions secret APT_GPG_PRIVATE_KEY.
#
# WHY YOU (NOT CI) MUST RUN THIS
#   The private key is a long-lived secret you own. It must be generated by you,
#   stored in your control, and added to the repository secrets via your GitHub
#   account. CI only ever sees it through the encrypted secret.
#
# REQUIREMENTS: gnupg, and (optionally) the GitHub CLI `gh` to set the secret
# automatically. Run from the repository root.

set -o errexit
set -o nounset
set -o pipefail

KEY_NAME="${KEY_NAME:-oob-usb-serial APT signing key}"
KEY_EMAIL="${KEY_EMAIL:-diaznet@users.noreply.github.com}"
KEY_COMMENT="${KEY_COMMENT:-oob-usb-serial repository}"
REPO_SLUG="${REPO_SLUG:-diaznet/oob-usb-serial}"

PUBKEY_OUT="docs/apt/pubkey.gpg"
PRIVKEY_OUT="apt-signing-private-key.asc"   # local only; DO NOT COMMIT

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v gpg >/dev/null 2>&1 || die "gnupg (gpg) is required."

mkdir -p "$(dirname "$PUBKEY_OUT")"

say "Generating a GPG signing key: ${KEY_NAME} <${KEY_EMAIL}>"
warn "This creates an unattended (no-passphrase) key suitable for CI."
warn "If you prefer a passphrase, edit this script and also add an"
warn "APT_GPG_PASSPHRASE secret + pass it in the workflow."

# Batch key generation parameters.
GEN_PARAMS="$(mktemp)"
cat > "$GEN_PARAMS" <<EOF
%no-protection
Key-Type: RSA
Key-Length: 4096
Subkey-Type: RSA
Subkey-Length: 4096
Name-Real: ${KEY_NAME}
Name-Comment: ${KEY_COMMENT}
Name-Email: ${KEY_EMAIL}
Expire-Date: 0
%commit
EOF

# Use an isolated temporary keyring so we do not touch the user's default one.
GNUPGHOME="$(mktemp -d)"
export GNUPGHOME
chmod 700 "$GNUPGHOME"

gpg --batch --gen-key "$GEN_PARAMS"
rm -f "$GEN_PARAMS"

# Identify the key we just made.
FPR="$(gpg --list-keys --with-colons "$KEY_EMAIL" | awk -F: '/^fpr:/{print $10; exit}')"
[ -n "$FPR" ] || die "could not determine key fingerprint"
say "Key fingerprint: ${FPR}"

# Export public key (armored) for users and the repo.
gpg --armor --export "$FPR" > "$PUBKEY_OUT"
say "Wrote public key -> ${PUBKEY_OUT} (commit this)"

# Export private key (armored) for the GitHub secret.
gpg --armor --export-secret-keys "$FPR" > "$PRIVKEY_OUT"
chmod 600 "$PRIVKEY_OUT"
say "Wrote private key -> ${PRIVKEY_OUT} (KEEP SECRET, DO NOT COMMIT)"

echo
say "Next steps"
cat <<EOF

1. Add the PRIVATE key as a GitHub Actions secret named APT_GPG_PRIVATE_KEY.

   Using the GitHub CLI (recommended):
     gh secret set APT_GPG_PRIVATE_KEY < "${PRIVKEY_OUT}" --repo ${REPO_SLUG}

   Or via the web UI:
     Settings -> Secrets and variables -> Actions -> New repository secret
     Name:  APT_GPG_PRIVATE_KEY
     Value: (paste the entire contents of ${PRIVKEY_OUT})

2. Commit the PUBLIC key:
     git add ${PUBKEY_OUT}
     git commit -m "Add APT repository signing public key"

3. Delete the local private key file once the secret is set:
     shred -u "${PRIVKEY_OUT}"   # or: rm -P / rm

4. Enable GitHub Pages for the repo (Settings -> Pages -> Source: gh-pages).

The APT publish workflow will import APT_GPG_PRIVATE_KEY and sign the archive
automatically on every release.
EOF

# Clean up the temporary keyring (the exported files are what matter).
rm -rf "$GNUPGHOME"
